### ISSUE TITLE
Problem in creating a Kit Item

### ISSUE THREAD

**Issue by tudorian** [nursix/eden#40]
def budget_kit_totals(kit_id):
    """
        Calculate Totals for a Kit
    """

    db = current.db
    s3db = current.s3db

    # Lookup all item quantities in this kit
    ltable = s3db.budget_kit_item
    query = (ltable.kit_id == kit_id) & \
            (ltable.deleted == False)

the error is 

AttributeError: 'Table' object has no attribute 'kit_id'

**Comment by tudorian** [comment]
ltable.kit_id does not exits

**Comment by nursix** [comment]
Solved by:
https://github.com/nursix/eden/commit/1c77fba50f78156860d73fc2a0ea1165f855492e
