### ISSUE TITLE
Error with postgres driver, cant persist data

### ISSUE THREAD

**Issue by ovnicraft** [nursix/eden#61]
With a fresh installation, in Debian 7 i change to use postgresql as DB using [this](https://gist.github.com/ovnicraft/ab17044f307221b9dc6d0c7479622475l) to deploy from [our fork](https://github.com/desastre-ecuador/eden/commit/669f8b5105bd508ab019c1ffea0a1b6559567169) but i got the error:

object has no attribute INVERT = current.db._adapter.INVERT

i found this at https://github.com/sahana/eden/blob/master/modules/s3/s3data.py#L112
I am using psycopg2 driver and try both installations from debian repo an pip but nothing works.

**Comment by nursix** [comment]
Please revert to web2py 2.14.5 to solve this problem.

  cd /home/web2py
  git reset --hard 81d0291

The PyDAL is currently undergoing a major restructuring, breaking backwards-compatibility and thereby loads of our code. Until this is settled, and our code adapted accordingly please use 2.14.5.
